version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - BACKEND_ENV=prd
    restart: unless-stopped
